--Dimenion/Fact Table Population


--Populate Dim_Date
INSERT INTO `cis9440-nyc-traffic.nyc_crashes_dataset.Dim_Date` (
    Date_PK, CRASH_DATE, CRASH_TIME, CRASH_HOUR, CRASH_DAY_OF_WEEK
)
SELECT DISTINCT
    FARM_FINGERPRINT(CONCAT(`CRASH DATE`, `CRASH TIME`)) AS Date_PK,
    CAST(`CRASH DATE` AS DATE) AS CRASH_DATE,
    PARSE_TIME('%H:%M', `CRASH TIME`) AS CRASH_TIME,
    EXTRACT(HOUR FROM PARSE_TIME('%H:%M', `CRASH TIME`)) AS CRASH_HOUR,
    CAST(EXTRACT(DAYOFWEEK FROM CAST(`CRASH DATE` AS DATE)) AS STRING) AS CRASH_DAY_OF_WEEK
FROM
    `cis9440-nyc-traffic.nyc_crashes_dataset.nyc_crashes`
WHERE `CRASH DATE` IS NOT NULL AND `CRASH TIME` IS NOT NULL;


--Populate Dim_Location
INSERT INTO `cis9440-nyc-traffic.nyc_crashes_dataset.Dim_Location` (
    Location_PK, BOROUGH, ZIP_CODE, LOCATION, ON_STREET_NAME
)
SELECT DISTINCT
    FARM_FINGERPRINT(CONCAT(BOROUGH, `ON STREET NAME`)) AS Location_PK,
    BOROUGH,
    CAST(`ZIP CODE` AS STRING) AS ZIP_CODE,
    LOCATION,
    `ON STREET NAME`
FROM
    `cis9440-nyc-traffic.nyc_crashes_dataset.nyc_crashes`
WHERE
    BOROUGH IS NOT NULL
    AND `ON STREET NAME` IS NOT NULL;


--Populate Dim_Contributing_Factor
INSERT INTO `cis9440-nyc-traffic.nyc_crashes_dataset.Dim_Contributing_Factor` (
    Factor_PK, CONTRIBUTING_FACTOR
)
SELECT DISTINCT
    FARM_FINGERPRINT(`CONTRIBUTING FACTOR VEHICLE 1`) AS Factor_PK,
    `CONTRIBUTING FACTOR VEHICLE 1` AS CONTRIBUTING_FACTOR
FROM
    `cis9440-nyc-traffic.nyc_crashes_dataset.nyc_crashes`
WHERE `CONTRIBUTING FACTOR VEHICLE 1` IS NOT NULL;


--Populate Dim_Vehicle
INSERT INTO `cis9440-nyc-traffic.nyc_crashes_dataset.Dim_Vehicle` (
    Vehicle_PK, VEHICLE_TYPE_CODE
)
SELECT DISTINCT
    FARM_FINGERPRINT(`VEHICLE TYPE CODE 1`) AS Vehicle_PK,
    `VEHICLE TYPE CODE 1` AS VEHICLE_TYPE_CODE
FROM
    `cis9440-nyc-traffic.nyc_crashes_dataset.nyc_crashes`
WHERE `VEHICLE TYPE CODE 1` IS NOT NULL;


--Populate Fact_Crashes
INSERT INTO `cis9440-nyc-traffic.nyc_crashes_dataset.Fact_Crashes` (
    Collision_ID, Date_FK, Location_FK,
    NUMBER_OF_PERSONS_INJURED, NUMBER_OF_PERSONS_KILLED,
    NUMBER_OF_PEDESTRIANS_INJURED, NUMBER_OF_PEDESTRIANS_KILLED,
    NUMBER_OF_CYCLIST_INJURED, NUMBER_OF_CYCLIST_KILLED,
    NUMBER_OF_MOTORIST_INJURED, NUMBER_OF_MOTORIST_KILLED,
    Factor_1_FK, Vehicle_Type_1_FK
)
SELECT
    CAST(T1.COLLISION_ID AS STRING) AS Collision_ID,
    FARM_FINGERPRINT(CONCAT(T1.`CRASH DATE`, T1.`CRASH TIME`)) AS Date_FK,
    FARM_FINGERPRINT(CONCAT(T1.BOROUGH, T1.`ON STREET NAME`)) AS Location_FK,
    CAST(COALESCE(T1.`NUMBER OF PERSONS INJURED`, 0) AS INT64),
    CAST(COALESCE(T1.`NUMBER OF PERSONS KILLED`, 0) AS INT64),
    CAST(COALESCE(T1.`NUMBER OF PEDESTRIANS INJURED`, 0) AS INT64),
    CAST(COALESCE(T1.`NUMBER OF PEDESTRIANS KILLED`, 0) AS INT64),
    CAST(COALESCE(T1.`NUMBER OF CYCLIST INJURED`, 0) AS INT64),
    CAST(COALESCE(T1.`NUMBER OF CYCLIST KILLED`, 0) AS INT64),
    CAST(COALESCE(T1.`NUMBER OF MOTORIST INJURED`, 0) AS INT64),
    CAST(COALESCE(T1.`NUMBER OF MOTORIST KILLED`, 0) AS INT64),
    FARM_FINGERPRINT(T1.`CONTRIBUTING FACTOR VEHICLE 1`) AS Factor_1_FK,
    FARM_FINGERPRINT(T1.`VEHICLE TYPE CODE 1`) AS Vehicle_Type_1_FK
FROM
    `cis9440-nyc-traffic.nyc_crashes_dataset.nyc_crashes` AS T1
WHERE 
    T1.BOROUGH IS NOT NULL
    AND T1.`ON STREET NAME` IS NOT NULL;




