-- motor_vehicle_crashes (raw data from Google Cloud)
CREATE TABLE nyc_traffic.motor_vehicle_crashes (
    CRASH_DATE DATE,
    CRASH_TIME TIME,
    BOROUGH VARCHAR(50),
    ZIP_CODE VARCHAR(10),
    LATITUDE FLOAT(10, 8),
    LONGITUDE FLOAT(11, 8),
    LOCATION VARCHAR(255),
    ON_STREET_NAME VARCHAR(100),
    CROSS_STREET_NAME VARCHAR(100),
    OFF_STREET_NAME VARCHAR(100),
    NUMBER_OF_PERSONS_INJURED INT,
    NUMBER_OF_PERSONS_KILLED INT,
    NUMBER_OF_PEDESTRIANS_INJURED INT,
    NUMBER_OF_PEDESTRIANS_KILLED INT,
    NUMBER_OF_CYCLIST_INJURED INT,
    NUMBER_OF_CYCLIST_KILLED INT,
    NUMBER_OF_MOTORIST_INJURED INT,
    NUMBER_OF_MOTORIST_KILLED INT,
    CONTRIBUTING_FACTOR_VEHICLE_1 VARCHAR(100),
    CONTRIBUTING_FACTOR_VEHICLE_2 VARCHAR(100),
    CONTRIBUTING_FACTOR_VEHICLE_3 VARCHAR(100),
    CONTRIBUTING_FACTOR_VEHICLE_4 VARCHAR(100),
    CONTRIBUTING_FACTOR_VEHICLE_5 VARCHAR(100),
    COLLISION_ID INT NOT NULL,
    VEHICLE_TYPE_CODE_1 VARCHAR(100),
    VEHICLE_TYPE_CODE_2 VARCHAR(100),
    VEHICLE_TYPE_CODE_3 VARCHAR(100),
    VEHICLE_TYPE_CODE_4 VARCHAR(100),
    VEHICLE_TYPE_CODE_5 VARCHAR(100),
    PRIMARY KEY (COLLISION_ID)
);

-- Dim_Date
CREATE TABLE nyc_traffic.Dim_Date (
    Date_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CRASH_DATE DATE NOT NULL,
    CRASH_TIME TIME NOT NULL,
    CRASH_HOUR INT,
    CRASH_DAY_OF_WEEK VARCHAR(10)
);

-- Dim_Location
CREATE TABLE nyc_traffic.Dim_Location (
    Location_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BOROUGH VARCHAR(50),
    ZIP_CODE VARCHAR(10),
    LATITUDE FLOAT(10, 8),
    LONGITUDE FLOAT(11, 8),
    ON_STREET_NAME VARCHAR(100),
    CROSS_STREET_NAME VARCHAR(100),
    OFF_STREET_NAME VARCHAR(100)
);

-- Dim_Contributing_Factor
CREATE TABLE nyc_traffic.Dim_Contributing_Factor (
    Factor_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CONTRIBUTING_FACTOR VARCHAR(100) NOT NULL UNIQUE
);

-- Dim_Vehicle
CREATE TABLE nyc_traffic.Dim_Vehicle (
    Vehicle_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VEHICLE_TYPE_CODE VARCHAR(100) NOT NULL UNIQUE
);

-- Fact_Crashes
CREATE TABLE nyc_traffic.Fact_Crashes (
    COLLISION_ID INT NOT NULL PRIMARY KEY,
    Date_FK INT NOT NULL,
    Location_FK INT NOT NULL,
    Factor_1_FK INT,
    Factor_2_FK INT,
    Factor_3_FK INT,
    Factor_4_FK INT,
    Factor_5_FK INT,
    Vehicle_Type_1_FK INT,
    Vehicle_Type_2_FK INT,
    Vehicle_Type_3_FK INT,
    Vehicle_Type_4_FK INT,
    Vehicle_Type_5_FK INT,
    NUMBER_OF_PERSONS_INJURED INT,
    NUMBER_OF_PERSONS_KILLED INT,
    NUMBER_OF_PEDESTRIANS_INJURED INT,
    NUMBER_OF_PEDESTRIANS_KILLED INT,
    NUMBER_OF_CYCLIST_INJURED INT,
    NUMBER_OF_CYCLIST_KILLED INT,
    NUMBER_OF_MOTORIST_INJURED INT,
    NUMBER_OF_MOTORIST_KILLED INT,
    FOREIGN KEY (Date_FK) REFERENCES Dim_Date(Date_PK),
    FOREIGN KEY (Location_FK) REFERENCES Dim_Location(Location_PK),
    FOREIGN KEY (Factor_1_FK) REFERENCES Dim_Contributing_Factor(Factor_PK),
    FOREIGN KEY (Factor_2_FK) REFERENCES Dim_Contributing_Factor(Factor_PK),
    FOREIGN KEY (Factor_3_FK) REFERENCES Dim_Contributing_Factor(Factor_PK),
    FOREIGN KEY (Factor_4_FK) REFERENCES Dim_Contributing_Factor(Factor_PK),
    FOREIGN KEY (Factor_5_FK) REFERENCES Dim_Contributing_Factor(Factor_PK),
    FOREIGN KEY (Vehicle_Type_1_FK) REFERENCES Dim_Vehicle(Vehicle_PK),
    FOREIGN KEY (Vehicle_Type_2_FK) REFERENCES Dim_Vehicle(Vehicle_PK),
    FOREIGN KEY (Vehicle_Type_3_FK) REFERENCES Dim_Vehicle(Vehicle_PK),
    FOREIGN KEY (Vehicle_Type_4_FK) REFERENCES Dim_Vehicle(Vehicle_PK),
    FOREIGN KEY (Vehicle_Type_5_FK) REFERENCES Dim_Vehicle(Vehicle_PK)
);